### ISSUE TITLE
Possible to hide line numbers but keep collapsible sections?

### ISSUE THREAD

**Issue by cosmotek** [akvelon/flutter-code-editor#159]
The title pretty much says it all. I've tried to do this by messing with the line number styling but it appears it also effects the collapsible buttons too.

Thanks! Keep up the great work. This package is amazing.

**Comment by yescorp** [comment]
Hey! 
There is no interface to justify your needs yet. If you fork the repo, you can hide line numbers column by changing the GutterWidget in `lib/src/gutter.dart`.

**Comment by alexeyinkin** [comment]
@cosmotek thanks for the suggestion, we will do it.

1. Soft rename `LineNumberStyle` to `GutterStyle`.
2. Add `GutterStyle.showLineNumbers` as `bool`.

**Comment by cosmotek** [comment]
Is this released?
