### ISSUE TITLE
Recommendations for implementing search highlighter

### ISSUE THREAD

**Issue by cosmotek** [akvelon/flutter-code-editor#160]
This seems like something that could be possible given the existing API, but I am having trouble finding a workable solution. I figured I would ask the authors here... Is it possible to implement search highlighting similar to other editors? My eventual goal is to allow for path-based queries against JSON. I realize I will have to handle the actual lookup myself, but I have no idea how to handle the rendering in this tool. Would it be possible to programmatically select a word or line? Or alternatively, would it be possible to get the absolute position of some text, in order to render an overlay highlighter?

I really appreciate any info you can provide. Thanks!

**Comment by alexeyinkin** [comment]
## Programmatic selection
```dart
codeController.value = codeController.value.copyWith(
  selection: ...
);
```

If you know the text:
```dart
codeController.value = codeController.value.selected('text', 123); // start position
```

## Absolute position of a character:
https://github.com/akvelon/flutter-code-editor/blob/d0fd022aeef3bf569dc14d8dbd1481d3c9919067/lib/src/code_field/code_field.dart#L417-L430

I am thinking of making this function reusable but have not yet found a nice way.

**Comment by cosmotek** [comment]
I wasn't able to get your programmatic selection example to work.

**Comment by alexeyinkin** [comment]
If you have a program that is supposed to work but does not, then please create a new issue with the minimal reproducible example. We will look into it.

Closing this as not a work-unit for the team.
