### ISSUE TITLE
Hello, thank you very much for seeing this library

### ISSUE THREAD

**Issue by peter100u** [akvelon/flutter-code-editor#173]
Hello, thank you very much for seeing this library, but it is still a little short of the features of codemirror. I hope to provide more features, such as automatic line wrap, matching (), {}. I hope to refer to more features（ https://codemirror.net/ ）

**Comment by alexeyinkin** [comment]
Thanks @peter100u 
I have created separate issues for your requests:
- #191 
- #192 

These are of low priority for us though, we cannot provide an ETA.
