### ISSUE TITLE
Use theme colors in error message popups

### ISSUE THREAD

**Issue by alexeyinkin** [akvelon/flutter-code-editor#212]
Currently we have black-on-black in Playground light theme:

1. Go to https://play-dev.beam.apache.org
2. Delete any parentheses:

![image](https://user-images.githubusercontent.com/44893228/231470162-5ebdcaed-e9d8-4788-8a4d-b918560a38d4.png)

**Comment by yescorp** [comment]
- Will be fixed in #223 

Also, `CodeField` supports customization of colors in `ErrorPopup` by providing

```
gutterStyle: GutterStyle(
                errorPopupTextStyle: TextStyle(
  color: Colors.black,
  backgroundColor: Colors.white,
  ),
),
```
