### ISSUE TITLE
Unable to change font family

### ISSUE THREAD

**Issue by MrCyjaneK** [akvelon/flutter-code-editor#237]
I've created a simple function to change all styles to use RobotoMono font in my app:

```dart
Map<String, TextStyle> getRobotoMonoFonts(Map<String, TextStyle> theme) {
  final Map<String, TextStyle> ret = {};
  for (var key in theme.keys) {
    ret[key] = theme[key]!.copyWith(fontFamily: "RobotoMono");
  }
  return ret;
}
```

and I call it in the following way:

```dart
CodeTheme(
  data: CodeThemeData(
    styles: getRobotoMonoFonts(monokaiSublimeTheme),
  ),
  child: SingleChildScrollView(
    child: CodeField(
      controller: codeCtrl,
    ),
  ),
),
```

![obraz](https://user-images.githubusercontent.com/20381330/236238148-e95786c6-b073-44ef-b576-3574108bd6f1.png)

But not every part of code is being updated to monospace. I've also tried manually editing these fields in CodeThemeData: `commentStyle, functionStyle, keywordStyle, paramsStyle, quoteStyle, titleStyle, variableStyle` but also without any success on getting the full code to switch to RobotoMono.

**Comment by yescorp** [comment]
Hello, @MrCyjaneK
Please, try to pass a `textStyle` parameter to the `CodeField` and specify the `fontFamily` there.

```dart
CodeField(
  textStyle: const TextStyle(
    fontFamily: 'RobotoMono',
    fontSize: 12,
  ),
)
```

The text inside of a `CodeField` mainly has the style, passed to its constructor. Styles from `CodeThemeData` only override the styles for specific text, like comments, keywords, etc.

**Comment by MrCyjaneK** [comment]
that.. that solved all my issues. Thanks.
