### ISSUE TITLE
Improve "Hot keys" feature for the code editor

### ISSUE THREAD

**Issue by VladMatyunin** [akvelon/flutter-code-editor#24]

**Comment by alexeyinkin** [comment]
Blocked as we don't know the hotkeys to implement.

**Comment by alexeyinkin** [comment]
Hot keys:
- Ctrl-C, Ctrl-Insert.
- Ctrl-V, Shift-Insert.
- Ctrl-X.
- Ctrl-A.
- Ctrl-Z.
