### ISSUE TITLE
Show specific sections only

### ISSUE THREAD

**Issue by VladMatyunin** [akvelon/flutter-code-editor#27]

**Comment by alexeyinkin** [comment]
Blocked as the requirements are not confirmed.
Requirements draft: https://docs.google.com/document/d/1m4XkWPCOtTG6cAa92p_nciB3K7laCgIvjNSQiHuJvFU/edit#heading=h.7pu3sakdzkf

**Comment by alexeyinkin** [comment]
https://github.com/akvelon/flutter-code-editor/pull/104
