### ISSUE TITLE
Line numbers

### ISSUE THREAD

**Issue by muhsintr** [akvelon/flutter-code-editor#270]
Line numbers are not aligned with code lines.
<img width="142" alt="Screenshot 2024-05-04 at 10 09 08" src="https://github.com/akvelon/flutter-code-editor/assets/79056821/537235ca-f6a7-48b5-9d83-9b1cb12fa241">

As attached, line numbers in the left side (80-83) are above expected position.

**Comment by franklin83diaz** [comment]
in my case the solution was added height: 1.5 to the gutterStyle

```
 ...
 child: ListView(
          children: [
            CodeField(
              controller: controller,
              minLines: 20,
              gutterStyle: const GutterStyle(
                textStyle: TextStyle(color: Colors.grey, height: 1.5),
                showLineNumbers: true,
              ),
              onChanged: (text) {
                print(text);
              },
            ),
          ],
        ),
...
```

**Comment by muhsintr** [comment]
> in my case the solution was added height: 1.5 to the gutterStyle
> 
> ```
>  ...
>  child: ListView(
>           children: [
>             CodeField(
>               controller: controller,
>               minLines: 20,
>               gutterStyle: const GutterStyle(
>                 textStyle: TextStyle(color: Colors.grey, height: 1.5),
>                 showLineNumbers: true,
>               ),
>               onChanged: (text) {
>                 print(text);
>               },
>             ),
>           ],
>         ),
> ...
> ```

It worked. Thanks a lot :)
