### ISSUE TITLE
Disabling Analyzer

### ISSUE THREAD

**Issue by albe-jj** [akvelon/flutter-code-editor#279]
I could not find a way to disable the code Analyzer. Is it possible? Otherwise it would be nice if the default `analyzer` for `CodeController` is no analyzer.

**Comment by jabguru** [comment]
@albe-jj have you found a way or an alternative?

**Comment by jabguru** [comment]
@albe-jj you can do that simply using the below code snippet

```
class NoAnalysis extends AbstractAnalyzer {
  const NoAnalysis();

  @override
  Future<AnalysisResult> analyze(Code code) async {
    return const AnalysisResult(issues: []);
  }
}
```

**Comment by albe-jj** [comment]
it works, thanks!
