### ISSUE TITLE
Comply with the original license

### ISSUE THREAD

**Issue by alexeyinkin** [akvelon/flutter-code-editor#29]
This editor was forked from https://github.com/BertrandBev/code_field
which uses MIT License. It means we must do one of the following:

- Mention the original author. Learn if MIT allows re-licensing to Apache license we currently use.
- Mention the original author. Re-license our fork to MIT license.
- Ask the original author to re-license the code under Apache license or public domain license.

**Comment by VladMatyunin** [comment]
it seems like our License already mentions the author. Alexey, can you please explore, do we need to put the license info to each of the files at the top?

**Comment by alexeyinkin** [comment]
License in each file is not required:

> No. This is strictly an ASF policy. Other projects using the Apache License should still refer to the [license's appendix](https://www.apache.org/licenses/LICENSE-2.0.html#apply) for guidance on applying a header to their source files.

https://www.apache.org/legal/src-headers.html#faq-nonasf
