### ISSUE TITLE
Replace tabs with spaces when loading the code

### ISSUE THREAD

**Issue by alexeyinkin** [akvelon/flutter-code-editor#62]
There was an issue in Beam Playground that suggests that tab symbols are not handled correctly in the editor:
https://issues.apache.org/jira/browse/BEAM-13446

Check this and fix if needed.

**Comment by nausharipov** [comment]
I'll look into it as soon as I find a Windows device. It works fine on Mac.

**Comment by alexeyinkin** [comment]
A Flutter bug prevents us from handling tabs, we will be tracking it internally here:
- https://github.com/akvelon/flutter-code-editor/issues/67

So the new scope here is to replace tabs with spaces in incoming text.
