### ISSUE TITLE
Ctrl + Z combination changes the code in editor but not the value of the Catalog field

### ISSUE THREAD

**Issue by Untouchamp** [akvelon/flutter-code-editor#74]
**Precondition:**
"Sample A" - current example.
"Sample B" - an example we will be switching to.
User is on the main page. Example "Sample A" is opened in editor.

**Steps to reproduce:**

1. Type anything in editor.
2. Click on the dropdown with examples.
3. Pick any other example.
4. The example in the editor switched to the selected one (Sample B is our current example now).
5. Press Ctrl + Z in the editor

**Expected Result:** 
Nothing happens. (According to the prod page)
**Acutal Result:** 
Previous example "Sample A" appears, but selected value in the Catalog dropdown field stays the same.

**Comment by alexeyinkin** [comment]
Test branch was: `pg_23415_akvelon-editor_from-23304`

**Comment by nausharipov** [comment]
The reason is that input history is saved after setting controller text: 

```
class Experiment extends StatelessWidget {
  const Experiment({super.key});

  @override
  Widget build(BuildContext context) {
    final TextEditingController controller = TextEditingController();
    return MaterialApp(
      home: Scaffold(
        body: Column(
          children: [
            // 1. Type anything in the text field
            // 2. Press the button to set text
            // 3. Press ctr+z
            // Previously typed text is visible.
            TextField(
              controller: controller,
            ),
            ElevatedButton(
              onPressed: () {
                controller.text = 'some text';
              },
              child: const Text('Set some text'),
            ),
          ],
        ),
      ),
    );
  }
}
```

I haven't found a method to clear input history of TextField. Should I open an issue or ask on StackOverflow?

**Comment by alexeyinkin** [comment]
I think this can be solved by adding `key` to `CodeField` which will re-create the editor state when changing an example or SDK. So no need for posting there.

**Comment by alexeyinkin** [comment]
Fixed in https://github.com/apache/beam/pull/23900
