### ISSUE TITLE
Selected area doesn't highlights when selecting text with keyboard and mouse

### ISSUE THREAD

**Issue by Untouchamp** [akvelon/flutter-code-editor#76]
**Precondition:**
User is on the main page. (Could be reproduced in Dark Mode as well)

**Steps to reproduce:**

1. Open any example
2. Select text with extended selection (scrolling during selection), using SHIFT/CTRL buttons or using mouse

**Expected Result:**
Selected text highlights with blue color.
**Acutal Result:**
Selection is practically invisible, hard to recognize selected part.

https://user-images.githubusercontent.com/87672816/193514723-71657f15-088f-4b53-bec4-0bb46bc3fd03.mp4

**Comment by alexeyinkin** [comment]
Not reproducible.
