### ISSUE TITLE
The cursor becomes invisible if you put it NOT at the end of the line

### ISSUE THREAD

**Issue by Untouchamp** [akvelon/flutter-code-editor#77]
**Precondition:**
User is on the main page. (Could be reproduced in Dark Mode as well)

**Steps to reproduce:**

1. Open any example
2. Put the cursor at the end of the line
3. Put the cursor in the middle of the line

**Expected Result:**
The cursor is visible wherever user places it.
**Acutal Result:**
The cursor becomes almost invisible if user places it in the middle of the line.

https://user-images.githubusercontent.com/87672816/193516071-2504915e-308d-4d69-bd58-7ea663a61c54.mp4

https://user-images.githubusercontent.com/87672816/193516107-58d013c0-4a87-4427-ae82-1faa001ea1a3.mp4

**Comment by alexeyinkin** [comment]
Not reproducible.
